Food/Areas/Admin/Controllers/CategoryController.cs
using Food.DataAccess.Repository.IRepository;
using Food.Models;
using Food.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Food.Controllers

{   
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Pomyślnie dodano nową kategorię";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            // var categoryFromDbSingle = _db.Categories.SingletOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Pomyślnie edytowano kategorię";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            // var categoryFromDbSingle = _db.Categories.SingletOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Pomyślnie usunięto kategorię";
            return RedirectToAction("Index");
        }
    }
}

Food/Areas/Admin/Controllers/DishController.cs
using Food.DataAccess.Repository.IRepository;
using Food.Models;
using Food.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using Food.Utility;

namespace Food.Controllers

{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)] 
    public class DishController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
     
        public DishController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }
    
        public IActionResult Index()
        {           
            return View();
        }      
        public IActionResult Upsert(int? id)
        {
            DishVM dishVM = new()
            {
                Dish = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                LevelTypeList = _unitOfWork.LevelType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };
           
            if (id == null || id == 0)
            {           
                return View(dishVM);
            }
            else
            {
                dishVM.Dish = _unitOfWork.Dish.GetFirstOrDefault(u => u.Id == id);
                return View(dishVM);
            }                
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(DishVM obj, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file!=null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\dish");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Dish.ImageUrl!=null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Dish.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using(var fileStreams = new FileStream(Path.Combine(uploads,fileName+extension),FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Dish.ImageUrl = @"\images\dish\" + fileName + extension;
                }
                if (obj.Dish.Id == 0)
                {
                    _unitOfWork.Dish.Add(obj.Dish);
                }
                else
                {
                    _unitOfWork.Dish.Update(obj.Dish);
                }              
                _unitOfWork.Save();
                TempData["success"] = "Potrawę dodano pomyślnie";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
     
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var dishList = _unitOfWork.Dish.GetAll(includeProperties:"Category,LevelType");
            return Json(new { data = dishList });
        }

        [HttpDelete]      
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Dish.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Błąd przy usuwaniu" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.Dish.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Usuwanie powiodło się" });
        }
        #endregion
    }
    
}

Food/Areas/Admin/Controllers/LevelTypeController.cs
using Food.DataAccess.Repository.IRepository;
using Food.Models;
using Food.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Food.Controllers

{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class LevelTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public LevelTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<LevelType> objLevelTypeList = _unitOfWork.LevelType.GetAll();
            return View(objLevelTypeList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LevelType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.LevelType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Pomyślnie dodano nowy poziom trudności";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var LevelTypeFromDbFirst = _unitOfWork.LevelType.GetFirstOrDefault(u => u.Id == id);

            if (LevelTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(LevelTypeFromDbFirst);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(LevelType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.LevelType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Pomyślnie edytowano poziom trudności";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var LevelTypeFromDbFirst = _unitOfWork.LevelType.GetFirstOrDefault(u => u.Id == id);

            if (LevelTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(LevelTypeFromDbFirst);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.LevelType.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.LevelType.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Pomyślnie usunięto poziom trudności";
            return RedirectToAction("Index");
        }
    }
}

Food/Views/Shared/_Layout.cshtml
@using Food.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Food.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Strona główna</a>
                            </li>   
                            @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">  
                                <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Kategorie</a>
                            </li>
                            <li class="nav-item">  
                                <a class="nav-link" asp-area="Admin" asp-controller="LevelType" asp-action="Index">Poziom trudności</a> 
                            </li>
                            <li class="nav-item">  
                                <a class="nav-link" asp-area="Admin" asp-controller="Dish" asp-action="Index">Potrawy </a> 
                            </li>
                        }
                    </ul>
                        <partial name="_LoginPartial" />
                    </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Food/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    <h2>@TempData["success"]</h2>
    </script>
}

@if(TempData["error"] != null)
{
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    <h2>@TempData["error"]</h2>
    </script>
}